server {
    listen 80;
    server_name kamoved.ru www.kamoved.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://kamoved.ru$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.kamoved.ru;

    ssl_certificate /etc/letsencrypt/live/kamoved.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kamoved.ru/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://kamoved.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name kamoved.ru;

    ssl_certificate /etc/letsencrypt/live/kamoved.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kamoved.ru/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $kamoved_upstream http://kamoved-frontend:80;

        proxy_pass $kamoved_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
