server {
    listen 80;
    server_name kamoved.ru www.kamoved.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://kamoved.ru$request_uri;
    }
}
