CREATE TABLE journal_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    execution_status VARCHAR(50) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    prepayment_amount NUMERIC(14, 2),
    total_amount NUMERIC(14, 2) NOT NULL,
    fulfillment_method VARCHAR(40),
    delivery_address TEXT,
    comment TEXT,
    created_by BIGINT NOT NULL REFERENCES app_user(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_journal_entry_type
        CHECK (type IN ('SALE', 'ORDER')),
    CONSTRAINT chk_journal_entry_payment_status
        CHECK (payment_status IN ('UNPAID', 'PREPAID', 'PAID')),
    CONSTRAINT chk_journal_entry_execution_status
        CHECK (execution_status IN (
            'NEW',
            'ORDERED_FACTORY',
            'IN_PRODUCTION',
            'READY_FACTORY',
            'IN_TRANSIT_TO_WAREHOUSE',
            'AT_WAREHOUSE',
            'OUT_FOR_DELIVERY',
            'COMPLETED',
            'CANCELLED'
        )),
    CONSTRAINT chk_journal_entry_fulfillment_method
        CHECK (fulfillment_method IS NULL OR fulfillment_method IN (
            'PICKUP_WAREHOUSE',
            'PICKUP_FACTORY',
            'DELIVERY'
        )),
    CONSTRAINT chk_journal_entry_prepayment_amount
        CHECK (prepayment_amount IS NULL OR prepayment_amount >= 0),
    CONSTRAINT chk_journal_entry_total_amount
        CHECK (total_amount >= 0)
);

CREATE INDEX idx_journal_entry_created_at ON journal_entry(created_at DESC);
CREATE INDEX idx_journal_entry_execution_status ON journal_entry(execution_status);
