CREATE TABLE journal_entry_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entry(id),
    catalog_product_id BIGINT,
    name VARCHAR(500) NOT NULL,
    quantity NUMERIC(14, 3) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    line_total NUMERIC(14, 2) NOT NULL,
    CONSTRAINT chk_journal_entry_item_quantity CHECK (quantity > 0),
    CONSTRAINT chk_journal_entry_item_unit_price CHECK (unit_price >= 0),
    CONSTRAINT chk_journal_entry_item_line_total CHECK (line_total >= 0),
    CONSTRAINT chk_journal_entry_item_unit
        CHECK (unit IN ('PIECE', 'SQUARE_METER', 'LINEAR_METER', 'PACKAGE'))
);

CREATE INDEX idx_journal_entry_item_entry ON journal_entry_item(journal_entry_id);

