CREATE TABLE entry_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entry(id),
    type VARCHAR(20) NOT NULL,
    name VARCHAR(255),
    phone VARCHAR(100),
    normalized_phone VARCHAR(30),
    comment TEXT,
    CONSTRAINT chk_entry_contact_type CHECK (type IN ('CLIENT', 'ADDITIONAL')),
    CONSTRAINT chk_entry_contact_not_empty CHECK (
        name IS NOT NULL OR phone IS NOT NULL OR comment IS NOT NULL
    )
);

CREATE INDEX idx_entry_contact_entry ON entry_contact(journal_entry_id);
CREATE INDEX idx_entry_contact_normalized_phone ON entry_contact(normalized_phone);
