CREATE TABLE journal_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entry(id),
    amount NUMERIC(14, 2) NOT NULL,
    payment_method VARCHAR(30),
    comment TEXT,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES app_user(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    voided_at TIMESTAMP WITH TIME ZONE,
    voided_by BIGINT REFERENCES app_user(id),
    correction_of_id BIGINT UNIQUE REFERENCES journal_payment(id),
    correction_reason TEXT,
    CONSTRAINT chk_journal_payment_amount CHECK (amount > 0),
    CONSTRAINT chk_journal_payment_method CHECK (
        payment_method IS NULL OR payment_method IN (
            'CASH',
            'BANK_ACCOUNT',
            'CARD',
            'PERSONAL_TRANSFER'
        )
    ),
    CONSTRAINT chk_journal_payment_correction CHECK (
        (correction_of_id IS NULL AND correction_reason IS NULL)
        OR (correction_of_id IS NOT NULL AND correction_reason IS NOT NULL)
    )
);

CREATE INDEX idx_journal_payment_entry ON journal_payment(journal_entry_id);
CREATE INDEX idx_journal_payment_received_at ON journal_payment(received_at);

INSERT INTO journal_payment (
    journal_entry_id,
    amount,
    payment_method,
    comment,
    received_at,
    created_by,
    created_at
)
SELECT
    entry.id,
    CASE
        WHEN entry.type = 'SALE' OR entry.payment_status = 'PAID' THEN entry.total_amount
        ELSE entry.prepayment_amount
    END,
    NULL,
    NULL,
    entry.created_at,
    entry.created_by,
    entry.created_at
FROM journal_entry entry
WHERE (entry.type = 'SALE' OR entry.payment_status IN ('PAID', 'PREPAID'))
  AND CASE
      WHEN entry.type = 'SALE' OR entry.payment_status = 'PAID' THEN entry.total_amount
      ELSE entry.prepayment_amount
  END > 0;

ALTER TABLE journal_entry DROP COLUMN prepayment_amount;

UPDATE journal_entry
SET payment_status = 'UNPAID'
WHERE total_amount = 0;
