ALTER TABLE app_user
    ADD COLUMN email VARCHAR(320);

ALTER TABLE app_user
    ADD CONSTRAINT uk_app_user_email UNIQUE (email);

CREATE TABLE email_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key VARCHAR(255) NOT NULL UNIQUE,
    recipient_user_id BIGINT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    text_body TEXT NOT NULL,
    html_body TEXT,
    status VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processing_started_at TIMESTAMP WITH TIME ZONE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    sent_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_email_notification_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES app_user (id),
    CONSTRAINT chk_email_notification_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT')),
    CONSTRAINT chk_email_notification_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_email_notification_due
    ON email_notification (status, next_attempt_at, id);

CREATE INDEX idx_email_notification_processing
    ON email_notification (status, processing_started_at);

CREATE INDEX idx_email_notification_recipient
    ON email_notification (recipient_user_id);
